package org.example.minutes.entity;

// Generated 2014/02/17 1:32:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MeetingType generated by hbm2java
 */
public class MeetingType extends EntityBase implements java.io.Serializable {

	private BigDecimal rid;
	private String type;
	private String name;
	private Set meetingMembers = new HashSet(0);
	private Set meetingForms = new HashSet(0);

	public MeetingType() {
	}

	public MeetingType(BigDecimal rid, String type, String name,
			boolean available, Date createDate, String createUser,
			Date updateDate, String updateUser) {
		this.rid = rid;
		this.type = type;
		this.name = name;
		setBaseColumnsValue(available, createDate, createUser,
				updateDate, updateUser);
	}

	public MeetingType(BigDecimal rid, String type, String name,
			boolean available, Date createDate, String createUser,
			Date updateDate, String updateUser, String comments,
			Set meetingMembers, Set meetingForms) {
		this.rid = rid;
		this.type = type;
		this.name = name;
		this.meetingMembers = meetingMembers;
		this.meetingForms = meetingForms;
		
		setBaseColumnsValue(available, createDate, createUser,
				updateDate, updateUser, comments);
		
	}

	public BigDecimal getRid() {
		return this.rid;
	}

	public void setRid(BigDecimal rid) {
		this.rid = rid;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getMeetingMembers() {
		return this.meetingMembers;
	}

	public void setMeetingMembers(Set meetingMembers) {
		this.meetingMembers = meetingMembers;
	}

	public Set getMeetingForms() {
		return this.meetingForms;
	}

	public void setMeetingForms(Set meetingForms) {
		this.meetingForms = meetingForms;
	}

}
