package org.example.minutes.entity;

// Generated 2014/02/17 1:32:41 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * MeetingForm generated by hbm2java
 */
public class MeetingForm extends EntityBase implements java.io.Serializable {

	private BigDecimal rid;
	private Meeting meeting;
	private MeetingType meetingType;

	public MeetingForm() {
	}

	public MeetingForm(BigDecimal rid, Meeting meeting,
			MeetingType meetingType, boolean available, Date createDate,
			String createUser, Date updateDate, String updateUser) {
		this.rid = rid;
		this.meeting = meeting;
		this.meetingType = meetingType;
		setBaseColumnsValue(available, createDate, createUser,
				updateDate, updateUser);
	}

	public MeetingForm(BigDecimal rid, Meeting meeting,
			MeetingType meetingType, boolean available, Date createDate,
			String createUser, Date updateDate, String updateUser,
			String comments) {
		this.rid = rid;
		this.meeting = meeting;
		this.meetingType = meetingType;
		setBaseColumnsValue(available, createDate, createUser,
				updateDate, updateUser, comments);
	}

	public BigDecimal getRid() {
		return this.rid;
	}

	public void setRid(BigDecimal rid) {
		this.rid = rid;
	}

	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	public MeetingType getMeetingType() {
		return this.meetingType;
	}

	public void setMeetingType(MeetingType meetingType) {
		this.meetingType = meetingType;
	}
}
